### ISSUE TITLE
Declare dev dependencies as such

### ISSUE THREAD

**Issue by pierreis** [MichalZalecki/react-boilerplate-lite#3]
Hello,

First of all, thanks for your work and blog posts! Really helps getting started.
I do have one question about this boilerplate –– is there any strong reason to declare heavy dependencies such as Babel and Webpack as runtime?
My first intuition is that in almost any case, Babel would be declared as a dev dependency?

I agree that it doesn't matter much in this case as Webpack takes care of excluding unimported dependencies – just wondering.

Thanks.

--
P.

**Comment by MichalZalecki** [comment]
@pierreis Thanks! The main reason that those aren't listed as dev dependencies is that Heroku has `NPM_CONFIG_PRODUCTION` set to `true` [[more info](https://devcenter.heroku.com/articles/nodejs-support#devdependencies)]. This results in installing only dependencies from `"dependencies"` array. Since you need both Babel and Webpack to build your project on Heroku they can't be listed as `devDependencies`.
